sonar.projectKey=DAHAP
sonar.projectName=DAHAP
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.

sonar.cfamily.compile-commands=build/compile_commands.json

sonar.exclusions=build/**,httplib.h,json.hpp
sonar.test.inclusions=test_algoritmos.cpp
sonar.coverage.exclusions=main.cpp
